name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "1 */12 * * *" # runs every hour, 30th min UTC (else use * * * * * for every minute)

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
       - uses: anmol098/waka-readme-stats@master 
         with: 
           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} 
           GH_TOKEN: ${{ secrets.GH_TOKEN }} 
           SHOW_SHORT_INFO: "False" 
           SHOW_PROFILE_VIEWS: "False" 
           SHOW_PROJECTS: "False" 
           SHOW_LINES_OF_CODE: "True" 
           SHOW_LOC_CHART: "False" 
           LOCALE: "en" 
           SHOW_OS: "False" 
           SHOW_DAYS_OF_WEEK: "False" 
           SHOW_COMMIT: "True"
           SYMBOL_VERSION: 1
           SHOW_UPDATED_DATE: "False"
           SHOW_LANGUAGE_PER_REPO: "False"
           COMMIT_MESSAGE: "Updated with Wakatime Metrics" 
           COMMIT_USERNAME: "wakatime-autobot"

    #  - uses: athul/waka-readme@master
    #    with:
    #      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
   
